// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqqboxzharzedgqdljfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxcWJveHpoYXJ6ZWRncWRsamZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNTYxMTAsImV4cCI6MjA1MzgzMjExMH0.nbuH45JMEDBMJLZOCa6I3FIpToo4Ws9R5s1o44C7k0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);